name: learn-github-actions

run-name: ${{ github.actor }} is learning GitHub Actions

on: push

env:
  PATCH: ${{ github.run_number }}


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Docker Image
        run: |
          docker build --build-arg PATCHNUM=${PATCH} -t rotemberk/maven-app:1.0.${PATCH} .

      - name: Push to DockerHub
        run: |
          echo "${{ secrets.DOCKERHUBTOKEN }} " | docker login -u rotemberk --pasword-stdin
          docker push rotemberk/maven-app:1.0.${PATCH}
