name: learn-github-actions

run-name: ${{ github.actor }} is learning GitHub Actions
  
on: push

env:
  PATCH: ${{ github.run_number }}


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Docker Image
        run: |
          docker build --build-arg PATCHNUM=${PATCH} -t rotemberk/maven-app:1.0.${PATCH} .

      - name: Push to DockerHub
        run: |
          echo "${{ secrets.DOCKERHUBTOKEN }}" | docker login -u "rotemberk" --password-stdin
          docker push rotemberk/maven-app:1.0.${PATCH}

      - name: Deploy Image
        run: |
          echo "${{ secrets.PRIVATE_KEY_TO_EC2 }}" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ubuntu@44.205.248.137 '
            echo "${{ secrets.DOCKERHUBTOKEN }}" | docker login -u "rotemberk" --password-stdin
            #   docker stop app || true
            # docker rm app || true
            # docker rmi rotemberk/maven-app || true
            docker pull rotemberk/maven-app:1.0.${PATCH}
            docker run -d --name app rotemberk/maven-app:1.0.${PATCH}

          '
